# safety_gate.py

# Purpose:
# Evaluates safety KPIs and decides whether release is allowed.

import json
import sys
from pathlib import Path

# Path to KPI file generated by simulation layer
KPI_FILE = Path("artifacts/simulation/kpi_results.json")

# Safety thresholds (simplified example)
MAX_DECELERATION = 8.0        # m/s^2
MIN_TTC = 1.5                # seconds
MIN_SCENARIO_COVERAGE = 0.9  # 90%

print("[SAFETY] Executing safety gate checks...")

# 1. Check KPI file existence
if not KPI_FILE.exists():
    print("[SAFETY] KPI file not found. Blocking release.")
    sys.exit(1)

# 2. Load KPI results
with KPI_FILE.open("r") as f:
    kpi = json.load(f)

# 3. Safety checks
violations = []

if kpi.get("collision", True):
    violations.append("Collision detected")

if kpi.get("min_ttc", 0) < MIN_TTC:
    violations.append(f"TTC below threshold ({kpi.get('min_ttc')}s)")

if kpi.get("max_deceleration", 999) > MAX_DECELERATION:
    violations.append(f"Excessive deceleration ({kpi.get('max_deceleration')} m/s^2)")

if kpi.get("scenario_coverage", 0) < MIN_SCENARIO_COVERAGE:
    violations.append(f"Insufficient scenario coverage ({kpi.get('scenario_coverage')})")

# 4. Decision
if violations:
    print("[SAFETY] SAFETY GATE FAILED")
    for v in violations:
        print(f" - {v}")
    sys.exit(1)

print("[SAFETY] All safety checks passed")
print("[SAFETY] Release approved")
